@echo off

SET PORT=5555
SET WEB_AUTH_KEY=123456789

SET KEY=1111111
SET SECRET=22222222222

SET EXCHANGE=demo
SET DEMO_EXCHANGE=poloniex

SET BALANCE_COIN=10
SET BALANCE_COIN_TWO=100


SET NAME_COIN=BTC
SET NAME_COIN_TWO=ltc
SET DEPOSIT_LIMIT=100%%
SET ONE_ORDERS_SELL=true
SET ONE_ORDERS_PROFIT_PERCENT=0.2
SET ONE_ORDERS_OFFSET=0.3
SET OFFSET_FIRST_ORDERS_PERCENT=0.1
SET OFFSET_ORDERS_PERCENT=0.2
SET COUNT_ORDERS=20
SET QUANTITY_ORDERS_IN_BLOCKS=5
SET SIZE_ORDERS_MARTINGALE=40%%
SET ONE_ORDERS_SPO_PERCENT=5
SET AUTO_EXIT_PERCENT=0

SET IGNORE_ORDERS_AT_START=false
SET TYPE_DATA_USED=active
SET SAVE_HISTORY=false

SET GREEDY_FIRST_ORDER_SIZE=0


SET TRAILING_STOP_PERCENT=0

SET DISABLE_CAPITALIZATION=true
SET CAPITALIZATION_BUY_ORDER=true
SET PARTIALLY_EXECUTED_GRID=true

SET FIRST_LOADING_HISTORY=true
SET CONTINUE_MARTINGALE_GRID=false

SET LOG=true
SET LOG_DEBUG=false
SET LOG_TRANSPORTS=0
SET LANGUAGE=ru

gbot-trader-win.exe
pause
