#!/bin/sh

export PORT=5555
export WEB_AUTH_KEY=123456789

export KEY=1111111
export SECRET=22222222222


export EXCHANGE=demo
export DEMO_EXCHANGE=poloniex

export BALANCE_COIN=10
export BALANCE_COIN_TWO=100


export NAME_COIN=BTC
export NAME_COIN_TWO=ltc
export DEPOSIT_LIMIT=100%
export ONE_ORDERS_SELL=true
export ONE_ORDERS_PROFIT_PERCENT=0.2
export ONE_ORDERS_OFFSET=0.3
export OFFSET_FIRST_ORDERS_PERCENT=0.1
export OFFSET_ORDERS_PERCENT=0.2
export COUNT_ORDERS=20
export QUANTITY_ORDERS_IN_BLOCKS=5
export SIZE_ORDERS_MARTINGALE=40%
export ONE_ORDERS_SPO_PERCENT=5
export AUTO_EXIT_PERCENT=0

export IGNORE_ORDERS_AT_START=false
export TYPE_DATA_USED=active
export SAVE_HISTORY=false

export GREEDY_FIRST_ORDER_SIZE=0


export TRAILING_STOP_PERCENT=0

export DISABLE_CAPITALIZATION=true
export CAPITALIZATION_BUY_ORDER=true
export PARTIALLY_EXECUTED_GRID=true

export FIRST_LOADING_HISTORY=true
export CONTINUE_MARTINGALE_GRID=false

export LOG=true
export LOG_DEBUG=false
export LOG_TRANSPORTS=0
export LANGUAGE=ru

./gbot-trader-macos

